#!/bin/bash

DIR=$(pwd)
USER=$(id -u)
GROUP=$(id -g)
CHANGE_OWNER=0
COMMAND=""
options=($@)

function fail {
    echo $1
    exit 1
}

while [ "${#options[@]}" -gt 0 ]; do
  case "${options[0]}" in
    --dpt-dir)
      DIR=$(realpath ${options[1]})
      if [ ! -d $DIR ]; then
        fail "Option ${options[0]} requires a path to a directory as an argument."
      fi
      options=(${options[@]:1})
      ;;
    --dpt-user)
      USER=${options[1]}
      options=(${options[@]:1})
      ;;
    --dpt-group)
      GROUP=${options[1]}
      options=(${options[@]:1})
      ;;
    --dpt-owner)
      CHANGE_OWNER=1
      ;;
    *)
      COMMAND="$COMMAND ${options[0]}"
      ;;
  esac
  options=(${options[@]:1})
done

echo "RUNNING: '$COMMAND' in directory '$DIR'"
docker run -it --rm \
    --volume $DIR:/app \
    --volume $SSH_AUTH_SOCK:/ssh-auth.sock \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --env SSH_AUTH_SOCK=/ssh-auth.sock \
    --user $USER:$GROUP \
    php-tools $COMMAND
if [ "$CHANGE_OWNER" -eq "1" ]; then
    echo "CHANGING OWNERSHIP TO $USER:$GROUP"
    sudo chown -R $USER:$GROUP $DIR
fi

